"""learning loops: job runs, recommendation outcomes, notification kind/target

Revision ID: 28ac7171f2a8
Revises: 90007f7de463
Create Date: 2026-08-08 01:14:38.789352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ac7171f2a8'
down_revision: Union[str, None] = '90007f7de463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_status'), ['status'], unique=False)

    op.create_table('recommendation_outcomes',
    sa.Column('rec_id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=40), nullable=False),
    sa.Column('habit_id', sa.String(length=32), nullable=True),
    sa.Column('shown_on', sa.Date(), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rec_id', 'shown_on', name='uq_recommendation_shown_once_per_day')
    )
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_habit_id'), ['habit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_rec_id'), ['rec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_shown_on'), ['shown_on'], unique=False)

    with op.batch_alter_table('notification_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('target', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_states_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_states_target'), ['target'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_states_target'))
        batch_op.drop_index(batch_op.f('ix_notification_states_kind'))
        batch_op.drop_column('target')
        batch_op.drop_column('kind')

    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_shown_on'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_rec_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_kind'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_habit_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_family'))

    op.drop_table('recommendation_outcomes')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_job_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_job_runs_job_id'))

    op.drop_table('job_runs')
    # ### end Alembic commands ###
